name: CI/CD for RPI Python Program

on:
  workflow_dispatch:  # Enable manual workflow runs

  

jobs:
  build_and_test:
    runs-on: ubuntu-latest  # Use Ubuntu runner for GitHub Actions

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        behave  # Replace with your test command, if different

    - name: Build and package
      run: |
        # Add build steps if necessary, e.g., packaging the Python application
        # For example:
        # python setup.py sdist bdist_wheel
