name: CI/CD for RPI Python Program

on:
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest  # Use Ubuntu runner for GitHub Actions

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify installation
      run: |
        pip list  # List installed packages to verify installation
        which behave  # Check if behave is in the PATH

    - name: Run tests
      run: |
        behave  # This should now work if behave is installed correctly

    - name: Build and package
      run: |
        # Add build steps if necessary, e.g., packaging the Python application